[target.'cfg(target_os="macos")']
rustflags = ["-C", "link-args=-framework CoreFoundation -framework Security"]
[net]
git-fetch-with-cli = true
[env]
RUST_MIN_STACK = "16777216"

[patch."https://github.com/scroll-tech/misc-precompiled-circuit.git"]
rmd160-circuits = { path='/home/combray/Code/zkevm/misc-precompiled-circuit' }